# Generated by Django 4.1 on 2022-08-30 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Modulo',
        ),
    ]
