# Generated by Django 4.1 on 2022-08-31 17:28

from django.db import migrations
from django.utils.text import slugify


def popular_slug(apps, schema_editor):
    Modulo = apps.get_model('modulos', 'Modulo')
    for modulo in Modulo.objects.all():
        modulo.slug = slugify(modulo.titulo)
        modulo.save()


class Migration(migrations.Migration):
    dependencies = [
        ('modulos', '0004_modulo_slug'),
    ]

    operations = [
        migrations.RunPython(popular_slug)
    ]
